package com.tmc.myapp;


import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Button;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.geom.Dimension;
import com.codename1.ui.layouts.GridLayout;

import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;
    private Button sadBtn, happyBtn, angryBtn, confusedBtn, surprisedBtn, scaredBtn;
    private GridLayout gl;
    public static Form hi;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        hi = new Form("How do you feel today?");
        hi.setLayout(GridLayout.autoFit());
        happyBtn = new Button("Happy");
        hi.addComponent(happyBtn);
        sadBtn = new Button("Sad");
        hi.addComponent(sadBtn);        
        confusedBtn = new Button("Confused");
        hi.addComponent(confusedBtn);
        angryBtn = new Button("Angry");
        hi.addComponent(angryBtn);
        scaredBtn = new Button("Scared");
        hi.addComponent(scaredBtn);
        surprisedBtn = new Button("Surprised");
        hi.addComponent(surprisedBtn);
        
        happyBtn.addActionListener(new ActionListener() {
        	@Override
        	public void actionPerformed(ActionEvent evt) {
        		new ShowQuotes().show();
        	}
        });
        hi.show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
